"""Perception and VLM feedback utilities."""

from .feedback import FeedbackError, StageEvent, VLMFeedbackProvider, VLMFeedbackReport
from .providers import (
    OraclePerception,
    PerceptionError,
    VLMDetection,
    VLMPerception,
    apply_drawer_target_world_bias,
    build_drawer_handle_prompt,
    build_drawer_front_blocker_prompt,
    build_drawer_safe_slot_prompt,
    build_vlm_functional_point_prompt,
    build_vlm_pose_prompt,
    capture_camera_frame,
    draw_detection_overlay,
    functional_point_quaternion_for_spec,
    normalize_detection_for_shape,
    parse_vlm_detection,
    parse_vlm_detection_optional,
    prepare_vlm_input_image,
    refine_drawer_handle_detection,
    refine_drawer_target_detection,
    refine_target_functional_detection,
    resolve_detection_pose,
    rescale_detection,
    visual_hint_for_object,
    world_pose_from_detection,
)

__all__ = [
    "FeedbackError",
    "StageEvent",
    "VLMFeedbackProvider",
    "VLMFeedbackReport",
    "OraclePerception",
    "PerceptionError",
    "VLMDetection",
    "VLMPerception",
    "apply_drawer_target_world_bias",
    "build_drawer_handle_prompt",
    "build_drawer_front_blocker_prompt",
    "build_drawer_safe_slot_prompt",
    "build_vlm_functional_point_prompt",
    "build_vlm_pose_prompt",
    "capture_camera_frame",
    "draw_detection_overlay",
    "functional_point_quaternion_for_spec",
    "normalize_detection_for_shape",
    "parse_vlm_detection",
    "parse_vlm_detection_optional",
    "prepare_vlm_input_image",
    "refine_drawer_handle_detection",
    "refine_drawer_target_detection",
    "refine_target_functional_detection",
    "resolve_detection_pose",
    "rescale_detection",
    "visual_hint_for_object",
    "world_pose_from_detection",
]
